apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword123
        - name: MYSQL_DATABASE
          value: bitnami_wordpress
        - name: MYSQL_USER
          value: bn_wordpress
        - name: MYSQL_PASSWORD
          value: wordpress123
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
